/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class', // Enable dark mode with class strategy
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Historic theme colors inspired by traditional card game aesthetics
        parchment: {
          50: '#FDFCFA',
          100: '#F9F7F3',
          200: '#F5F1E8',
          300: '#EBE4D7',
          400: '#DFD5C3',
          500: '#D1C4AE',
          600: '#B8A88E',
          700: '#9A8A73',
          800: '#7A6D5C',
          900: '#5C5349',
        },
        crimson: {
          50: '#FDF2F2',
          100: '#FBE4E4',
          200: '#F7C9C9',
          300: '#F19B9B',
          400: '#E76262',
          500: '#D63939',
          600: '#B82020',
          700: '#9A1818',
          800: '#7D1616',
          900: '#641616',
        },
        umber: {
          50: '#FBF8F5',
          100: '#F5EFE7',
          200: '#E8DBC9',
          300: '#D9C1A1',
          400: '#C79F6E',
          500: '#B8864D',
          600: '#A06730',
          700: '#85532A',
          800: '#6D4427',
          900: '#5A3922',
        },
        forest: {
          50: '#F4F8F5',
          100: '#E6F1E9',
          200: '#CCE3D2',
          300: '#A5CFAF',
          400: '#72B384',
          500: '#4A9760',
          600: '#357A49',
          700: '#2B633D',
          800: '#254F33',
          900: '#1F422B',
        },
        sapphire: {
          50: '#F2F6FB',
          100: '#E3EDF8',
          200: '#C1D9F0',
          300: '#8EBCE5',
          400: '#5499D6',
          500: '#2E79C2',
          600: '#1F5FA4',
          700: '#1A4C85',
          800: '#18406E',
          900: '#18365B',
        },
      },
      fontFamily: {
        serif: ['Georgia', 'Cambria', 'Times New Roman', 'serif'],
      },
      keyframes: {
        'slide-from-bottom': {
          '0%': { transform: 'translateY(300px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-from-top': {
          '0%': { transform: 'translateY(-300px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-from-left': {
          '0%': { transform: 'translateX(-300px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-from-right': {
          '0%': { transform: 'translateX(300px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'collect-to-bottom': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'translateY(200px) scale(0.5)', opacity: '0' },
        },
        'collect-to-top': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'translateY(-200px) scale(0.5)', opacity: '0' },
        },
        'collect-to-left': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'translateX(-200px) scale(0.5)', opacity: '0' },
        },
        'collect-to-right': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'translateX(200px) scale(0.5)', opacity: '0' },
        },
        'score-pop': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.3)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'points-float-up': {
          '0%': { transform: 'translateY(0)', opacity: '0' },
          '20%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { transform: 'translateY(-40px)', opacity: '0' },
        },
        'slideDown': {
          '0%': { transform: 'translate(-50%, -100%)', opacity: '0' },
          '100%': { transform: 'translate(-50%, 0)', opacity: '1' },
        },
        'slideUp': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fadeIn': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'slide-from-bottom': 'slide-from-bottom 0.4s ease-out',
        'slide-from-top': 'slide-from-top 0.4s ease-out',
        'slide-from-left': 'slide-from-left 0.4s ease-out',
        'slide-from-right': 'slide-from-right 0.4s ease-out',
        'collect-to-bottom': 'collect-to-bottom 1s ease-in-out forwards',
        'collect-to-top': 'collect-to-top 1s ease-in-out forwards',
        'collect-to-left': 'collect-to-left 1s ease-in-out forwards',
        'collect-to-right': 'collect-to-right 1s ease-in-out forwards',
        'score-pop': 'score-pop 0.5s ease-out',
        'points-float-up': 'points-float-up 2s ease-out forwards',
        'slideDown': 'slideDown 0.3s ease-out',
        'slideUp': 'slideUp 0.3s ease-out',
        'fadeIn': 'fadeIn 0.2s ease-in',
      },
    },
  },
  plugins: [],
}
